name = "MemoizedMethods"
uuid = "2f808968-54ae-4603-8d72-6e67d20f0a1c"
authors = ["Peter Ahrens <pahrens@mit.edu>",
           "Simon Kornblith <simon@simonster.com>",
           "CÃ©dric St-Jean <cedric.stjean@gmail.com>",
           "Kevin Squire <kevin.squire@gmail.com",
           "Contributors (https://github.com/JuliaCollections/Memoize.jl/graphs/contributors)"]
version = "0.1.2"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
MacroTools = "~0.4, ~0.5"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[targets]
test = ["Test", "Pkg"]
